BuildFIx

diff --git a/deploy.yaml b/deploy.yaml
--- a/deploy.yaml
+++ b/deploy.yaml
@@ -1,4 +1,3 @@
----
 name: Deploy
 
 # yamllint disable-line rule:truthy
@@ -23,7 +22,7 @@ jobs:
     name: ℹ️ Gather add-on information
     runs-on: ubuntu-latest
     outputs:
-      architectures: ${{ steps.information.outputs.architectures }}
+      architectures: ${{ steps.set_outputs.outputs.architectures }}
       build: ${{ steps.information.outputs.build }}
       description: ${{ steps.information.outputs.description }}
       environment: ${{ steps.release.outputs.environment }}
@@ -36,7 +35,23 @@ jobs:
         uses: actions/checkout@v4.2.2
       - name: 🚀 Run add-on information action
         id: information
-        uses: frenck/action-addon-information@v1.0.0
+        uses: frenck/action-addon-information@v1.4.2
+
+      - name: 🛠 Ensure architectures is valid JSON
+        id: set_outputs
+        run: |
+          arch_raw="${{ steps.information.outputs.architectures }}"
+          
+          # Convert space-separated values to JSON array if needed
+          if [[ "$arch_raw" != "["* ]]; then
+            arch_json=$(echo "$arch_raw" | jq -R 'split(" ")' | jq -c '.')
+          else
+            arch_json="$arch_raw"
+          fi
+          
+          echo "architectures=$arch_json" >> "$GITHUB_ENV"
+          echo "architectures=$arch_json" >> "$GITHUB_OUTPUT"
+
       - name: ℹ️ Gather version and environment
         id: release
         run: |
@@ -52,8 +67,9 @@ jobs:
               environment="beta"
             fi
           fi
-          echo "environment=${environment}" >> $GITHUB_OUTPUT
-          echo "version=\"${version}\"" >> $GITHUB_OUTPUT
+          echo "environment=${environment}" >> "$GITHUB_OUTPUT"
+          echo "version=\"${version}\"" >> "$GITHUB_OUTPUT"
+
   deploy:
     name: 👷 Build & Deploy ${{ matrix.architecture }}
     needs: information
@@ -64,6 +80,7 @@ jobs:
     steps:
       - name: ⤵️ Check out code from GitHub
         uses: actions/checkout@v4.2.2
+
       - name: 🏗 Set up build cache
         id: cache
         uses: actions/cache@v4.2.0
@@ -72,51 +89,45 @@ jobs:
           key: docker-${{ github.ref }}-${{ matrix.architecture }}-${{ github.sha }}
           restore-keys: |
             docker-${{ github.ref }}-${{ matrix.architecture }}
+
       - name: 🏗 Set up QEMU
         uses: docker/setup-qemu-action@v3.4.0
+
       - name: 🏗 Set up Docker Buildx
         uses: docker/setup-buildx-action@v3.9.0
+
       - name: ℹ️ Compose build flags
         id: flags
         run: |
-          echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
+          echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_OUTPUT"
           from=$(jq --raw-output ".build_from.${{ matrix.architecture }}" "${{ needs.information.outputs.build }}")
-          echo "from=${from}" >> $GITHUB_OUTPUT
-          if [[ "${{ matrix.architecture}}" = "amd64" ]]; then
-            echo "platform=linux/amd64" >> $GITHUB_OUTPUT
-          elif [[ "${{ matrix.architecture }}" = "i386" ]]; then
-            echo "platform=linux/386" >> $GITHUB_OUTPUT
-          elif [[ "${{ matrix.architecture }}" = "armhf" ]]; then
-            echo "platform=linux/arm/v6" >> $GITHUB_OUTPUT
-          elif [[ "${{ matrix.architecture }}" = "armv7" ]]; then
-            echo "platform=linux/arm/v7" >> $GITHUB_OUTPUT
-          elif [[ "${{ matrix.architecture }}" = "aarch64" ]]; then
-            echo "platform=linux/arm64/v8" >> $GITHUB_OUTPUT
-          else
-            echo "::error ::Could not determine platform for architecture ${{ matrix.architecture }}"
-            exit 1
-          fi
-      - name: 🏗  Login to GitHub Container Registry
+          echo "from=${from}" >> "$GITHUB_OUTPUT"
+
+          case "${{ matrix.architecture }}" in
+            amd64) echo "platform=linux/amd64" >> "$GITHUB_OUTPUT" ;;
+            i386) echo "platform=linux/386" >> "$GITHUB_OUTPUT" ;;
+            armhf) echo "platform=linux/arm/v6" >> "$GITHUB_OUTPUT" ;;
+            armv7) echo "platform=linux/arm/v7" >> "$GITHUB_OUTPUT" ;;
+            aarch64) echo "platform=linux/arm64/v8" >> "$GITHUB_OUTPUT" ;;
+            *) echo "::error ::Unknown platform for architecture ${{ matrix.architecture }}" && exit 1 ;;
+          esac
+
+      - name: 🏗 Login to GitHub Container Registry
         uses: docker/login-action@v3.3.0
         with:
           registry: ghcr.io
           username: ${{ secrets.GHCR_USERNAME }}
           password: ${{ secrets.GHCR_PASSWORD }}
+
       - name: 🚀 Build and push
         uses: docker/build-push-action@v6.13.0
         with:
           push: true
-          # yamllint disable rule:line-length
           tags: |
             ghcr.io/hassio-addons/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.environment }}
             ghcr.io/hassio-addons/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}
-          # yamllint enable rule:line-length
           context: ${{ needs.information.outputs.target }}
           file: ${{ needs.information.outputs.target }}/Dockerfile
-          cache-from: |
-            type=local,src=/tmp/.docker-cache
-            ghcr.io/hassio-addons/${{ needs.information.outputs.slug }}/${{ matrix.architecture }}:edge
-          cache-to: type=local,mode=max,dest=/tmp/.docker-cache
           platforms: ${{ steps.flags.outputs.platform }}
           build-args: |
             BUILD_ARCH=${{ matrix.architecture }}
@@ -127,14 +138,13 @@ jobs:
             BUILD_REF=${{ github.sha }}
             BUILD_REPOSITORY=${{ github.repository }}
             BUILD_VERSION=${{ needs.information.outputs.version }}
+
   publish-edge:
     name: 📢 Publish to edge repository
-    if: needs.information.outputs.environment == 'edge'
+    if: ${{ needs.information.outputs.environment == 'edge' }}
     needs:
       - information
       - deploy
-    environment:
-      name: ${{ needs.information.outputs.environment }}
     runs-on: ubuntu-latest
     steps:
       - name: 🚀 Dispatch repository updater update signal
@@ -149,52 +159,4 @@ jobs:
               "name": "${{ needs.information.outputs.name }}",
               "repository": "${{ github.repository }}",
               "version": "${{ needs.information.outputs.version }}"
-            }
-  publish-beta:
-    name: 📢 Publish to beta repository
-    if: |
-      needs.information.outputs.environment == 'beta' ||
-      needs.information.outputs.environment == 'stable'
-    needs:
-      - information
-      - deploy
-    environment:
-      name: ${{ needs.information.outputs.environment }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: 🚀 Dispatch repository updater update signal
-        uses: peter-evans/repository-dispatch@v1.1.3
-        with:
-          token: ${{ secrets.DISPATCH_TOKEN }}
-          repository: hassio-addons/repository-beta
-          event-type: update
-          client-payload: >
-            {
-              "addon": "${{ needs.information.outputs.slug }}",
-              "name": "${{ needs.information.outputs.name }}",
-              "repository": "${{ github.repository }}",
-              "version": "${{ github.event.release.tag_name }}"
-            }
-  publish-stable:
-    name: 📢 Publish to stable repository
-    if: needs.information.outputs.environment == 'stable'
-    needs:
-      - information
-      - deploy
-    environment:
-      name: ${{ needs.information.outputs.environment }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: 🚀 Dispatch repository updater update signal
-        uses: peter-evans/repository-dispatch@v1.1.3
-        with:
-          token: ${{ secrets.DISPATCH_TOKEN }}
-          repository: hassio-addons/repository
-          event-type: update
-          client-payload: >
-            {
-              "addon": "${{ needs.information.outputs.slug }}",
-              "name": "${{ needs.information.outputs.name }}",
-              "repository": "${{ github.repository }}",
-              "version": "${{ github.event.release.tag_name }}"
             }
